name = input("Enter your name: ")
age = int(input('Enter your age: '))
address = input('Enter your address: ')
print ('Your name is:', name)
print ('Your age is:', age)
print ('Your address is:', address)